---
- hosts: dbserver
  remote_user: vagrant
  sudo: yes
  vars:
    remote: false
    mariadb_root_password: 'password'
  roles:
    - {role: common}
    - {role: partition}
    - {role: redis}
    - {role: mariadb}
    - {role: mroonga}
  post_tasks:
    - name: reload vagrant
      sudo: no
      command: vagrant reload
      delegate_to: 127.0.0.1
      when: not remote
