---
- hosts: dbserver
  remote_user: vagrant
  sudo: yes
  vars:
    remote: false
    mariadb_root_password: 'password'
  roles:
    - {role: common}
    - {role: partition}
    - {role: redis}
    - {role: mariadb}
