---
- name: create swap image
  command: dd if=/dev/zero of=/swap.img bs=1M count=2024
  when: ansible_swaptotal_mb < 1

- name: chmod swap image
  command: chmod 600 /swap.img
  when: ansible_swaptotal_mb < 1

- name: mkswap
  command: mkswap /swap.img
  when: ansible_swaptotal_mb < 1

- name: activate swap
  command: swapon /swap.img
  when: ansible_swaptotal_mb < 1

- name: register fstab
  mount: name=swap src=/swap.img fstype=swap opts=defaults passno=0 dump=0 state=present
  when: ansible_swaptotal_mb < 1
