---
- name: create swap image
  command: dd if=/dev/zero of=/swap.img bs=1M count=2024
  when: ansible_swaptotal_mb < 1

- name: chmod swap image
  command: chmod 600 /swap.img
  when: ansible_swaptotal_mb < 1

- name: mkswap
  command: mkswap /swap.img
  when: ansible_swaptotal_mb < 1

- name: activate swap
  command: swapon /swap.img
  notify: reload vagrant
  when: ansible_swaptotal_mb < 1
