---
# equivalent to "mysql_secure_installation"

- name: install mariadb-server
  apt: name={{ item }} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: start service
  service: name=mysql
           state=started
           enabled=yes

- name: set the root password
  mysql_user: user=root password={{ mariadb_root_password }} host=localhost state=present

- name: config for easy access as root
  template: src=my.cnf.j2 dest=/root/.my.cnf mode=600

- name: config for easy access as {{ ansible_ssh_user }} user
  template: src=my.cnf.j2 dest=/home/{{ ansible_ssh_user }}/.my.cnf mode=600

- name: delete anonymous user for localhost
  mysql_user: user='' state=absent

- name: secure the root user
  mysql_user: user=root password={{ mariadb_root_password }} host={{ item }}
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
    - "{{ ansible_hostname }}"

- name: remove the MySQL test database
  mysql_db: db=test state=absent
