- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600

- name: install basic package
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - monit
    - ntp
    - ufw
    - vim
    - htop
    - sysstat

- name: install language-pack-ja
  apt: name=language-pack-ja state=latest

- name: locale-gen ja_JP.UTF-8
  command: /usr/sbin/locale-gen ja_JP.UTF-8

- name: update-locale LANG=ja_JP.UTF-8
  command: /usr/sbin/update-locale LANG=ja_JP.UTF-8

- name: Set /etc/localtime to Asia/Tokyo
  copy: src=/usr/share/zoneinfo/Asia/Tokyo
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Set timezone
  copy: content='Asia/Tokyo'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify: update timezone

- name: ufw enable
  ufw: state=enabled policy=deny
  notify: restart ufw

- name: ufw ssh config
  ufw: rule=limit port=ssh proto=tcp state=reloaded

- name: ufw detail config
  ufw: rule=allow port={{item}} proto=tcp state=reloaded
  with_items:
    - http
    - https

- name: be sure NTP is installed
  apt: name=ntp state=installed

- name: be sure NTP is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

- name: be sure ntpd is running
  service: name=ntp state=running enabled=yes
